export {default as LesserBat} from "./LesserBat.vue"
export {default as Bat} from "./Bat.vue"
export {default as GiantBat} from "./GiantBat.vue"
export {default as EvasiveBat} from "./EvasiveBat.vue"
// export {default as FrozenBat} from "./FrozenBat.vue"
export {default as Goblin} from "./Goblin.vue"
export {default as ShieldGoblin} from "./ShieldGoblin.vue"
export {default as ShieldBat} from "./ShieldBat.vue"
export {default as GoblinCamp} from "./GoblinCamp.vue"
